house/urls.py
from django.urls import path,include
from .views import houseListView,houseCreateView
from . import views

urlpatterns = [
    path('', houseListView.as_view(), name='home'),
    path('house/new/', houseCreateView.as_view(), name='housenew'),
    path('users/', include('users.urls')),
    path('q', views.house_filter, name='house_filter'),
    ]

project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('house.urls')),
]

users/urls.py
# users/urls.py
from django.urls import path, include
from .views import SignUpView, UserUpdateView, UserPasswordChangeView, UserPasswordResetView
 
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('change_password/', UserPasswordChangeView.as_view(), name='change_password'),
    path('reset_password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update_user'),
]

house/models.py
from django.db import models

# Create your models here.


class City(models.TextChoices):
    
    Keelung='KLU','基隆市'
    NewTaipei='TPH','新北市'
    Taipei='TPE','臺北市'
    Taoyuan='TYC','桃園市'
    HsinchuCounty='HSH','新竹縣'
    Hsinchu='HSC','新竹市'
    Miaoli='MAC','苗栗市'
    MiaoliCounty='MAL','苗栗縣'
    Taichung='TXG','臺中市'
    ChanghuaCounty='CWH','彰化縣'
    Changhua='CWS','彰化市'
    Nantou='NTC','南投市'
    NantouCounty='NTO','南投縣'
    Yunlin='YLH','雲林縣'
    ChiayiCounty='CHY','嘉義縣'
    Chiayi='CYI','嘉義市'
    Tainan='TNN','臺南市'
    Kaohsiung='KHH','高雄市'
    PingtungCounty='IUH','屏東縣'
    Pingtung='PTS','屏東市'
    YilanCounty='ILN','宜蘭縣'
    Yilan='ILC','宜蘭市'
    HualienCounty='HWA','花蓮縣'
    Hualien='HWC','花蓮市'
    Taitung='TTC','臺東市'
    TaitungCounty='TTT','臺東縣'
    Penghu='PEH','澎湖縣'
    Green='GNI','綠島'
    Orchid='KYD','蘭嶼'
    Kinmen='KMN','金門縣'
    Matsu='MZW','馬祖'
    Lienchiang='LNN','連江縣'



class room(models.TextChoices):
    B1 = '1', '1室1廳'
    B2 = '2', '2室1廳'
    B3 = '3', '3室1廳'
    B4 = '4', '4室2廳'


class Area(models.TextChoices):
    A1 = '1', '<50坪'
    A2 = '2', '50-70坪'
    A3 = '3', '70-90坪'
    A4 = '4', '90-140坪'
    A5 = '5', '>140坪'


class Floor(models.TextChoices):
    LOW = 'l', '低樓層'
    MIDDLE = 'm', '中樓層'
    HIGH = 'h', '高樓層'


class Direction(models.TextChoices):
    EAST = 'e', '東'
    SOUTH = 's', '南'
    WEST = 'w', '西'
    NORTH = 'n', '北'


class Community(models.Model):
    name = models.CharField(max_length=60, verbose_name='縣市')
    city = models.CharField(max_length=5, choices=City.choices, verbose_name="城市")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布日期")
    mod_date = models.DateTimeField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "縣市"
        verbose_name_plural = "縣市"

    def __str__(self):
        return self.name


class House(models.Model):
    description = models.CharField(max_length=108, verbose_name="描述")
    #city=models.CharField(max_length=10, choices=City.choices,null=True, verbose_name="城市")
    community = models.ForeignKey('Community', on_delete=models.CASCADE, verbose_name="縣市")
    address = models.CharField(max_length=30, verbose_name="地址") 
    phone = models.CharField(max_length=30 ,verbose_name="電話") 
    bedroom = models.CharField(max_length=1, choices=room.choices, verbose_name="房型")
    direction = models.CharField(max_length=2, choices=Direction.choices, verbose_name="朝向")
    floor = models.CharField(max_length=1, choices=Floor.choices, verbose_name="樓層")
    area = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="面積(平方米)")
    area_class = models.CharField(max_length=1, null=True, blank=True, choices=Area.choices, verbose_name="面積")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="月租")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="發布日期")
    mod_date = models.DateTimeField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "房子"
        verbose_name_plural = "房子"

    def __str__(self):
        return '{}.{}'.format(self.description, self.address)

    def save(self, *args, **kwargs):
        if self.area < 50:
            self.area_class = Area.A1
        elif 50 <= self.area < 70:
            self.area_class = Area.A2
        elif 70 <= self.area < 90:
            self.area_class = Area.A3
        elif 90 <= self.area < 140:
            self.area_class = Area.A4
        else:
            self.area_class = Area.A5

        super().save(*args, **kwargs)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date
from dateutil.relativedelta import relativedelta
 
class CustomUser(AbstractUser):
    # These are the fields we want on top of the fields included
    #  with the built-in Django User Model that come with:
    #  username, first_name, last_name, email, password, ....
    gender = models.CharField(max_length=255, blank=True, null=True)
    dob = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=255, blank=True, null=True)
 
    def __str__(self):
        return self.username
 
    def age(self):
        if self.dob == None:
            return None
        age = relativedelta(date.today(), self.dob)
        return age.years

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from bootstrap_datepicker_plus.widgets import DatePickerInput
from django import forms
 
 
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', )
 
class CustomUserChangeForm(UserChangeForm):
    password = None
 
    class Meta:
        model = CustomUser
        fields = ['username','email', 'first_name', 'last_name', 'dob', 'location' ]
        widgets = { 'dob': DatePickerInput() }
 

house/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse
from .models import Community, House
from .filters import HouseFilter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

class houseListView(ListView):
    model = House
    template_name = 'home.html'
    

    
class houseCreateView(CreateView):
    model = House
    template_name = 'housenew.html'
    
    fields = ['description' ,'community','bedroom','direction','floor','area','price','phone' ]
 
    def get_success_url(self):
        
        return reverse('home')


# Filter houses
def house_filter(request):
    base_qs = House.objects.all().select_related('community')
    f = HouseFilter(request.GET, queryset=base_qs)
    paginator = Paginator(f.qs, 5)
    page = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    is_paginated = True if paginator.num_pages > 1 else False
    context = {'page_obj': page_obj, 'paginator': paginator, 'is_paginated': is_paginated, 'filter': f, }
    print(context)

    return render(request, 'home.html', context)

users/views.py
# users/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
 
class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'
 
class UserUpdateView(generic.UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('home')
    template_name = 'update.html'
 
    # This keeps users from accessing the profile of other users.
    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return CustomUser.objects.all()
        else:
            return CustomUser.objects.filter(id=user.id)
 
class UserPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('home')
    template_name = 'change_password.html'
 
class UserPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('login')
    template_name = 'reset_password.html'

house/templates/home.html
<!-- house/templates/home.html -->
{% extends 'base.html' %}
{% load core_tags_filters %}
{% load static %}
{% block content %}

  <form role="form" method="get" action="{% url 'house_filter' %}">
    <div class="input-group">

      <input type="text" name="q" value="{% if filter.form.q.value %}{{ filter.form.q.value }}{% endif %}" class="form-control" id="id_q" placeholder="請輸入縣市或是關鍵字">

      <div class="input-group-append">
          <button type="submit" class="btn btn-inline btn-sm bg-warning">
          <svg class="bi bi-search" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
            <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
          </svg>
          </button>
       </div>

    </div>
  </form>
  
<div class="table-responsive">
  <table class="table table-striped table-hover">
      <thead>
      <tr>
          <th scope="col">描述</th>
          <th scope="col">城市</th>
          <th scope="col">縣市</th>
          <th scope="col">房型</th>
          <th scope="col">朝向</th>
          <th scope="col">面積</th>
          <th scope="col">房租(月)</th>
          <th scope="col">連絡電話</th>
      </tr>
      </thead>
        <tbody>
      {% if page_obj %}
        
          {% for item in page_obj %}
          <tr>
              <td>{{ item.description }}</td>
              <td>{{ item.community.get_city_display }}</td>
              <td>{{ item.community }}</td>

              <td>{{ item.get_bedroom_display }}</td>
              <td>{{ item.get_direction_display }}</td>
              <td>{{ item.area }}</td>
              <td>{{ item.price }}</td>
              
              <td>{{ item.phone }}</td>
          </tr>
          {% endfor %}
      {% elif object_list %}
      {% for item in object_list %}
      <tr>
        <td>{{ item.description }}</td>
        <td>{{ item.community.get_city_display }}</td>
        <td>{{ item.community }}</td>

        <td>{{ item.get_bedroom_display }}</td>
        <td>{{ item.get_direction_display }}</td>
        <td>{{ item.area }}</td>
        <td>{{ item.price }}</td>
        
        <td>{{ item.phone }}</td>
      </tr>
      {% endfor %}
        {% endif %}
      </tbody>
  </table>

  {% if is_paginated %}
  <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}

      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
            <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
      {% endif %}
  </ul>
{% endif %}

</div>
{% endblock content %}

house/templates/housenew.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h4>刊登房屋</h4>
  <form action="" method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='Ok' %}{% endbuttons %}
  </form>
{% endblock content %}

templates/base.html
<!-- templates/base.html -->
{% extends 'bootstrap.html' %}
 
{% load bootstrap4 %}
 
{% block bootstrap4_content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">租屋網</a>
      <button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
 
      
 
        </ul>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'housenew' %}"><b>刊登房屋</b></a>
              </li>
            {% endif %}
          </ul>
     
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                  Welcome {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'update_user' user.pk %}">Profile</a>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                </div>
              </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
              </li>
            {% endif %}
          </ul>
    
      </div>
    </nav>
 
    <div class="container">
 
        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
 
        {% block content %}(no content){% endblock %}
    </div>
 
{% endblock %}

templates/bootstrap.html
<!-- templates/bootstrap.html -->
{% extends 'bootstrap4/bootstrap4.html' %}
 
{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

users/templates/change_password.html
<!-- users/templates/change_password.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

  <h4>Change Password</h4>
  <form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='Ok' %}{% endbuttons %}
  </form>

{% endblock content %}

users/templates/reset_password.html
<!-- users/templates/reset_password.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

  <h4>Reset Password</h4>
  <form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='Ok' %}{% endbuttons %}
  </form>

{% endblock content %}

users/templates/update.html
<!-- users/templates/update.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block extrascript %}
  {{ form.media }}
{% endblock %}

{% block content %}
  <h4>
    Profile
    <small><a href="{% url 'change_password' %}">(change password)</a></small>
  </h4>
  <form method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='Ok' %}{% endbuttons %}
  </form>
{% endblock content %}